/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conversor;

import static java.awt.event.KeyEvent.*;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author damt210
 */
public class Conversor extends javax.swing.JFrame {

    /**
     * Creates new form Conversor
     */
    public Conversor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        EntradaCelsius = new javax.swing.JTextField();
        Celsius = new javax.swing.JLabel();
        Fahrenheit = new javax.swing.JLabel();
        Convertir = new javax.swing.JButton();
        EntradaFahrenheit = new javax.swing.JTextField();
        limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor C a F");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EntradaCelsius.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EntradaCelsiusKeyPressed(evt);
            }
        });

        Celsius.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Celsius.setForeground(new java.awt.Color(0, 0, 0));
        Celsius.setText("ºC");

        Fahrenheit.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Fahrenheit.setForeground(new java.awt.Color(0, 0, 0));
        Fahrenheit.setText("ºF");

        Convertir.setBackground(new java.awt.Color(255, 204, 204));
        Convertir.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Convertir.setForeground(new java.awt.Color(0, 0, 0));
        Convertir.setText("CONVERTIR");
        Convertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertirActionPerformed(evt);
            }
        });

        EntradaFahrenheit.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        EntradaFahrenheit.setFocusable(false);

        limpiar.setBackground(new java.awt.Color(204, 255, 204));
        limpiar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        limpiar.setForeground(new java.awt.Color(0, 0, 0));
        limpiar.setText("LIMPIAR");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(EntradaCelsius, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(EntradaFahrenheit, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(limpiar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Convertir, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(9, 9, 9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Celsius, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(Fahrenheit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EntradaCelsius, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Celsius, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EntradaFahrenheit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fahrenheit, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(Convertir, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        EntradaCelsius.setText(null);
        EntradaFahrenheit.setText(null);
        EntradaCelsius.requestFocus();
    }//GEN-LAST:event_limpiarActionPerformed

    private void ConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertirActionPerformed
        
        
        String valorCelsius = EntradaCelsius.getText();
        double celsius;

        try {

            celsius = Double.parseDouble(valorCelsius);

            double fahrenheit;

            fahrenheit = (celsius * 9/5) + 32;

            EntradaFahrenheit.setText(Double.toString(fahrenheit));

        } catch (NumberFormatException e) {
            String error =e.getMessage();
            
            JOptionPane jop =new JOptionPane("Campo vacío", JOptionPane.INFORMATION_MESSAGE);
            JDialog dialog = jop.createDialog("ATENCIÓN");
            dialog.setLocation(Background.getLocationOnScreen().x + 300,Background.getLocationOnScreen().y);
            
            JOptionPane jop2 =new JOptionPane("Dato con coma", JOptionPane.ERROR_MESSAGE);
            JDialog dialog2 = jop2.createDialog("ERROR");
            dialog2.setLocation(Background.getLocationOnScreen().x + 300,Background.getLocationOnScreen().y);
            
            JOptionPane jop3 =new JOptionPane("Input erróneo", JOptionPane.ERROR_MESSAGE);
            JDialog dialog3 = jop3.createDialog("ERROR");
            dialog3.setLocation(Background.getLocationOnScreen().x + 300,Background.getLocationOnScreen().y);
            
            if(e.getMessage().contains("empty")){
            dialog.setVisible(true);
            EntradaFahrenheit.setText("");
            EntradaCelsius.requestFocus();
           
            }else if(e.getMessage().contains(",")){
            dialog2.setVisible(true);
            EntradaFahrenheit.setText("");
            EntradaCelsius.setText(null);
            EntradaCelsius.requestFocus();
            }else{
            dialog3.setVisible(true);
            EntradaFahrenheit.setText("");
            EntradaCelsius.setText(null);
            EntradaCelsius.requestFocus();
            }
            //System.out.println(error);
            
            
        }
        
    }//GEN-LAST:event_ConvertirActionPerformed

    private void EntradaCelsiusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EntradaCelsiusKeyPressed
        if (evt.getExtendedKeyCode()==VK_ENTER) Convertir.doClick();
        if (evt.getExtendedKeyCode()==VK_ESCAPE) System.exit(0);
    }//GEN-LAST:event_EntradaCelsiusKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conversor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Celsius;
    private javax.swing.JButton Convertir;
    private javax.swing.JTextField EntradaCelsius;
    private javax.swing.JTextField EntradaFahrenheit;
    private javax.swing.JLabel Fahrenheit;
    private javax.swing.JButton limpiar;
    // End of variables declaration//GEN-END:variables
}
