package componenteusersteam;

import java.io.File;
import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalTime;

/**
 *
 * @author Ramiro
 */
public class UserLogueado extends javax.swing.JPanel implements Serializable {

    /**
     * Creates new form UserLogueado
     */
    public UserLogueado() {
        initComponents();
        String fechaLogin1 = LocalDate.now()+ " " + LocalTime.now().getHour() + ":" +LocalTime.now().getMinute();
        jLabelDateLogin.setText(fechaLogin1);
        
    }
    private File rutaImagen;
    
    private String User;

    public String getUser() {
        return User;
    }

    public void setUser(String User) {
        this.User = User;
        jLabelUserName.setText(User);
    }

   
       
    
    

    public File getRutaImagen() {
        return rutaImagen;
    }

    public void setRutaImagen(File rutaImagen) {
        this.rutaImagen = rutaImagen;
        jpanel_Imagen1.setRutaImagen(rutaImagen);
    }

    public Jpanel_Imagen getJpanel_Imagen1() {
        return jpanel_Imagen1;
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jLabelUserName = new javax.swing.JLabel();
        jLabelDateLogin = new javax.swing.JLabel();
        jpanel_Imagen1 = new componenteusersteam.Jpanel_Imagen();

        jPanelFondo.setOpaque(false);

        jLabelUserName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelUserName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserName.setText("Nombre");

        jLabelDateLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelDateLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDateLogin.setText("Hora del login");

        javax.swing.GroupLayout jpanel_Imagen1Layout = new javax.swing.GroupLayout(jpanel_Imagen1);
        jpanel_Imagen1.setLayout(jpanel_Imagen1Layout);
        jpanel_Imagen1Layout.setHorizontalGroup(
            jpanel_Imagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 134, Short.MAX_VALUE)
        );
        jpanel_Imagen1Layout.setVerticalGroup(
            jpanel_Imagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelFondoLayout = new javax.swing.GroupLayout(jPanelFondo);
        jPanelFondo.setLayout(jPanelFondoLayout);
        jPanelFondoLayout.setHorizontalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jpanel_Imagen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDateLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );
        jPanelFondoLayout.setVerticalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpanel_Imagen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addComponent(jLabelUserName)
                        .addGap(28, 28, 28)
                        .addComponent(jLabelDateLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDateLogin;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JPanel jPanelFondo;
    private componenteusersteam.Jpanel_Imagen jpanel_Imagen1;
    // End of variables declaration//GEN-END:variables
}
