/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tareafederacion;

import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author damt210
 */
public class TareaFederacion extends javax.swing.JFrame {

    /**
     * Creates new form TareaFederacion
     */
    public TareaFederacion() {
        initComponents();
    }
    String apeNom = null;
    String equipo = null;

    public boolean compruebaApeNom() {
        if (jTextFieldApeNom.getText().isBlank()) {

            return false;
        } else {
            apeNom = jTextFieldApeNom.getText();
            return true;
        }

    }

    public boolean compruebaEquipo() {
        if (jComboBoxEquipo.getSelectedIndex() == 0) {

            return false;
        } else {
            equipo = jComboBoxEquipo.getSelectedItem().toString();
            return true;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        jLabel1ApeNom = new javax.swing.JLabel();
        jLabelEquipo = new javax.swing.JLabel();
        jTextFieldApeNom = new javax.swing.JTextField();
        jComboBoxEquipo = new javax.swing.JComboBox<>();
        jButtonAgregar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabelIcono = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingreso de datos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1ApeNom.setText("Apellidos y Nombre");
        Fondo.add(jLabel1ApeNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabelEquipo.setText("Equipo");
        Fondo.add(jLabelEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jTextFieldApeNom.setToolTipText("Introduzca Apellidos y Nombre");
        Fondo.add(jTextFieldApeNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 280, -1));

        jComboBoxEquipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>", "Real Madrid", "FC Barcelona", "RC Racing", "CB Betis" }));
        jComboBoxEquipo.setToolTipText("Seleccione un equipo de la lista");
        Fondo.add(jComboBoxEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 280, -1));

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.setToolTipText("Botón para agregar a la tabla");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        Fondo.add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.setToolTipText("Botón para limpiar los datos");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        Fondo.add(jButtonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, -1));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Apellidos y Nombre", "Equipo"
            }
        ));
        jScrollPane.setViewportView(jTable);

        Fondo.add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 460, 190));

        jLabelIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ESP256x.png"))); // NOI18N
        Fondo.add(jLabelIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 260, 260));

        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed

        if (compruebaApeNom() && compruebaEquipo()) {
            String[] entrada = {apeNom, equipo};
            DefaultTableModel modelo = (DefaultTableModel) jTable.getModel();

            modelo.addRow(entrada);
        } else if (!compruebaApeNom()) {
            JOptionPane.showMessageDialog(this, "Apellidos y nombre no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!compruebaEquipo()) {
            JOptionPane.showMessageDialog(this, "Seleccione un equiipo", "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        jTextFieldApeNom.setText("");
        jComboBoxEquipo.setSelectedIndex(0);
        jTextFieldApeNom.requestFocus();
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TareaFederacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TareaFederacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TareaFederacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TareaFederacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TareaFederacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JComboBox<String> jComboBoxEquipo;
    private javax.swing.JLabel jLabel1ApeNom;
    private javax.swing.JLabel jLabelEquipo;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextFieldApeNom;
    // End of variables declaration//GEN-END:variables
}
