/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniEncuesta;

/**
 *
 * @author Ramiro
 */
public class MiniEncuesta extends javax.swing.JFrame {

    /**
     * Creates new form MiniEncuesta
     */
    public MiniEncuesta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RadioSistema = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelSistema = new javax.swing.JLabel();
        jRadioButtonWindows = new javax.swing.JRadioButton();
        jRadioButtonMacOs = new javax.swing.JRadioButton();
        jRadioButtonLinux = new javax.swing.JRadioButton();
        jRadioButtonUbuntu = new javax.swing.JRadioButton();
        jRadioButtonOtros = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelEspecializacion = new javax.swing.JLabel();
        jCheckBoxProgramacion = new javax.swing.JCheckBox();
        jCheckBoxDisenoGrafico = new javax.swing.JCheckBox();
        jCheckBoxAdministracion = new javax.swing.JCheckBox();
        jLabelHoras = new javax.swing.JLabel();
        JLabelNumeroHoras = new javax.swing.JLabel();
        jSlider = new javax.swing.JSlider();
        jButtonGenerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("1_4_MiniEncuesta_Ramiro_Gutierrez_Valverde");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(450, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSistema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSistema.setText("Elige tu sistema operativo");
        jLabelSistema.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelSistema.setMaximumSize(new java.awt.Dimension(260, 30));
        jLabelSistema.setMinimumSize(new java.awt.Dimension(260, 30));
        jLabelSistema.setPreferredSize(new java.awt.Dimension(260, 30));
        jPanel1.add(jLabelSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 260, 30));

        RadioSistema.add(jRadioButtonWindows);
        jRadioButtonWindows.setText("Windows");
        jPanel1.add(jRadioButtonWindows, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        RadioSistema.add(jRadioButtonMacOs);
        jRadioButtonMacOs.setText("MacOs");
        jPanel1.add(jRadioButtonMacOs, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        RadioSistema.add(jRadioButtonLinux);
        jRadioButtonLinux.setText("Linux");
        jPanel1.add(jRadioButtonLinux, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        RadioSistema.add(jRadioButtonUbuntu);
        jRadioButtonUbuntu.setText("Ubuntu");
        jPanel1.add(jRadioButtonUbuntu, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        RadioSistema.add(jRadioButtonOtros);
        jRadioButtonOtros.setText("Otros");
        jPanel1.add(jRadioButtonOtros, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 320, 20));

        jLabelEspecializacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEspecializacion.setText("Elige tu campo de especialización");
        jLabelEspecializacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelEspecializacion.setMaximumSize(new java.awt.Dimension(260, 30));
        jLabelEspecializacion.setMinimumSize(new java.awt.Dimension(260, 30));
        jLabelEspecializacion.setPreferredSize(new java.awt.Dimension(260, 30));
        jPanel1.add(jLabelEspecializacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 260, 30));

        jCheckBoxProgramacion.setText("Programación");
        jPanel1.add(jCheckBoxProgramacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        jCheckBoxDisenoGrafico.setText("Diseño Gráfico");
        jPanel1.add(jCheckBoxDisenoGrafico, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        jCheckBoxAdministracion.setText("Administración");
        jPanel1.add(jCheckBoxAdministracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        jLabelHoras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHoras.setText("Horas de Uso o Visualización de Pantallas");
        jLabelHoras.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelHoras.setMaximumSize(new java.awt.Dimension(260, 30));
        jLabelHoras.setMinimumSize(new java.awt.Dimension(260, 30));
        jLabelHoras.setPreferredSize(new java.awt.Dimension(260, 30));
        jPanel1.add(jLabelHoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 260, 30));

        JLabelNumeroHoras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelNumeroHoras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        JLabelNumeroHoras.setPreferredSize(new java.awt.Dimension(42, 30));
        jPanel1.add(JLabelNumeroHoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, -1, 30));

        jSlider.setMinorTickSpacing(1);
        jPanel1.add(jSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 200, -1));

        jButtonGenerar.setText("Generar");
        jButtonGenerar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jButtonGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 530, 140, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiniEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiniEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiniEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiniEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiniEncuesta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelNumeroHoras;
    private javax.swing.ButtonGroup RadioSistema;
    private javax.swing.JButton jButtonGenerar;
    private javax.swing.JCheckBox jCheckBoxAdministracion;
    private javax.swing.JCheckBox jCheckBoxDisenoGrafico;
    private javax.swing.JCheckBox jCheckBoxProgramacion;
    private javax.swing.JLabel jLabelEspecializacion;
    private javax.swing.JLabel jLabelHoras;
    private javax.swing.JLabel jLabelSistema;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonLinux;
    private javax.swing.JRadioButton jRadioButtonMacOs;
    private javax.swing.JRadioButton jRadioButtonOtros;
    private javax.swing.JRadioButton jRadioButtonUbuntu;
    private javax.swing.JRadioButton jRadioButtonWindows;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider jSlider;
    // End of variables declaration//GEN-END:variables
}
