/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tareasaludador;

import static java.awt.event.KeyEvent.VK_ENTER;
import static java.awt.event.KeyEvent.VK_ESCAPE;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author damt210
 */
public class TareaSaludador extends javax.swing.JFrame {

    /**
     * Creates new form TareaSaludador
     */
    public TareaSaludador() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelInstruccion = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jButtonSaludar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tarea 1_2_Saludador_Ramiro_Gutierrez_Valverde");
        setLocation(new java.awt.Point(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelInstruccion.setText("Escribe un nombre al que saludar");
        jPanel1.add(jLabelInstruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 260, -1));

        jButtonSaludar.setText("¡Saludar!");
        jButtonSaludar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaludarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSaludar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaludarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaludarActionPerformed
        String nombre, textoMensaje;
        nombre = jTextFieldNombre.getText();

        if (nombre.matches("(.*\\d.*)")) {
            textoMensaje = ("Debes introducir un nombre");
            JOptionPane jop3 = new JOptionPane(textoMensaje, JOptionPane.ERROR_MESSAGE);
            JDialog dialog3 = jop3.createDialog("ERROR");
            dialog3.setLocationRelativeTo(null);
            jTextFieldNombre.setText(null);           
            dialog3.setVisible(true);
            jTextFieldNombre.requestFocus();
        } else if (nombre.isBlank()){
            textoMensaje = ("Debes introducir un nombre");
            JOptionPane jop2 = new JOptionPane(textoMensaje, JOptionPane.ERROR_MESSAGE);
            JDialog dialog2 = jop2.createDialog("ERROR");
            dialog2.setLocationRelativeTo(null);
            jTextFieldNombre.setText(null);
            dialog2.setVisible(true);
            jTextFieldNombre.requestFocus();
        } else {         
            textoMensaje = ("¡Hola " + nombre + "!");
            JOptionPane jop = new JOptionPane(textoMensaje, JOptionPane.INFORMATION_MESSAGE);
            JDialog dialog = jop.createDialog("Message");
            dialog.setLocationRelativeTo(null);
            jTextFieldNombre.setText(null);
            dialog.setVisible(true);
            jTextFieldNombre.requestFocus();

        }

    }//GEN-LAST:event_jButtonSaludarActionPerformed

    private void jTextFieldNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyPressed
        if (evt.getExtendedKeyCode()==VK_ENTER) jButtonSaludar.doClick();
        if (evt.getExtendedKeyCode()==VK_ESCAPE) System.exit(0);
    }//GEN-LAST:event_jTextFieldNombreKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TareaSaludador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TareaSaludador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TareaSaludador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TareaSaludador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TareaSaludador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSaludar;
    private javax.swing.JLabel jLabelInstruccion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
