/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package taller2023;

import javax.swing.JOptionPane;

/**
 *
 * @author damt210
 */
public class Sat_Agl extends javax.swing.JFrame {

    /**
     * Creates new form Sat_Agl
     */
    public Sat_Agl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanelFondo = new javax.swing.JPanel();
        jPanelGestionTaller = new javax.swing.JPanel();
        jButtonPortatil = new javax.swing.JButton();
        jButtonSobremesa = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuOrdenador = new javax.swing.JMenu();
        jMenuItemPortatil = new javax.swing.JMenuItem();
        jMenuItemSobremesa = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuVersion = new javax.swing.JMenu();
        jMenuItemv1 = new javax.swing.JMenuItem();
        jMenuItemv2 = new javax.swing.JMenuItem();
        jMenuItemAcerca = new javax.swing.JMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SAT_AGL");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelGestionTaller.setBackground(new java.awt.Color(177, 204, 139));
        jPanelGestionTaller.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestión del Taller", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanelGestionTaller.setForeground(new java.awt.Color(0, 0, 0));

        jButtonPortatil.setBackground(new java.awt.Color(0, 211, 224));
        jButtonPortatil.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonPortatil.setForeground(new java.awt.Color(0, 0, 0));
        jButtonPortatil.setText("Portátil");
        jButtonPortatil.setToolTipText("Ventana Portátil");
        jButtonPortatil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPortatilActionPerformed(evt);
            }
        });

        jButtonSobremesa.setBackground(new java.awt.Color(158, 112, 34));
        jButtonSobremesa.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonSobremesa.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSobremesa.setText("Sobremesa");
        jButtonSobremesa.setToolTipText("Ventana Sobremesa");
        jButtonSobremesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSobremesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGestionTallerLayout = new javax.swing.GroupLayout(jPanelGestionTaller);
        jPanelGestionTaller.setLayout(jPanelGestionTallerLayout);
        jPanelGestionTallerLayout.setHorizontalGroup(
            jPanelGestionTallerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGestionTallerLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButtonPortatil, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(jButtonSobremesa)
                .addGap(26, 26, 26))
        );
        jPanelGestionTallerLayout.setVerticalGroup(
            jPanelGestionTallerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGestionTallerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelGestionTallerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPortatil)
                    .addComponent(jButtonSobremesa))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanelFondo.add(jPanelGestionTaller, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 420, 90));

        getContentPane().add(jPanelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 470));

        jMenuBar1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jMenuOrdenador.setText("Ordenador");
        jMenuOrdenador.setToolTipText("menu ordenador");
        jMenuOrdenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuOrdenadorActionPerformed(evt);
            }
        });

        jMenuItemPortatil.setText("Portátil");
        jMenuItemPortatil.setToolTipText("Ventana Portátil");
        jMenuItemPortatil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPortatilActionPerformed(evt);
            }
        });
        jMenuOrdenador.add(jMenuItemPortatil);

        jMenuItemSobremesa.setText("Sobremesa");
        jMenuItemSobremesa.setToolTipText("Ventana sobremesa");
        jMenuItemSobremesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobremesaActionPerformed(evt);
            }
        });
        jMenuOrdenador.add(jMenuItemSobremesa);

        jMenuBar1.add(jMenuOrdenador);

        jMenuAyuda.setText("Ayuda");
        jMenuAyuda.setToolTipText("Menu Ayuda");

        jMenuVersion.setText("Versión");
        jMenuVersion.setToolTipText("Versión");

        jMenuItemv1.setText("V1.1");
        jMenuItemv1.setToolTipText("Primera versión");
        jMenuVersion.add(jMenuItemv1);

        jMenuItemv2.setText("V1.2");
        jMenuItemv2.setToolTipText("Segunda versión");
        jMenuVersion.add(jMenuItemv2);

        jMenuAyuda.add(jMenuVersion);

        jMenuItemAcerca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItemAcerca.setText("Acerca de...");
        jMenuItemAcerca.setToolTipText("Acerca de");
        jMenuItemAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAcercaActionPerformed(evt);
            }
        });
        jMenuAyuda.add(jMenuItemAcerca);

        jMenuBar1.add(jMenuAyuda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAcercaActionPerformed
        JOptionPane.showMessageDialog(this, "Gestión del taller V1.1", "Message", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItemAcercaActionPerformed

    private void jButtonPortatilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPortatilActionPerformed
        Portatil p = new Portatil(this, rootPaneCheckingEnabled);
        p.setLocationRelativeTo(this);
        p.setVisible(true);
    }//GEN-LAST:event_jButtonPortatilActionPerformed

    private void jMenuOrdenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuOrdenadorActionPerformed
        JOptionPane.showMessageDialog(this, "Ventana modal del botón Portátil", "Message", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuOrdenadorActionPerformed

    private void jButtonSobremesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSobremesaActionPerformed
        Sobremesa s = new Sobremesa(this, rootPaneCheckingEnabled);
        s.setLocationRelativeTo(this);
        s.setVisible(true);
    }//GEN-LAST:event_jButtonSobremesaActionPerformed

    private void jMenuItemPortatilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPortatilActionPerformed
         Portatil p = new Portatil(this, rootPaneCheckingEnabled);
        p.setLocationRelativeTo(this);
        p.setVisible(true);
    }//GEN-LAST:event_jMenuItemPortatilActionPerformed

    private void jMenuItemSobremesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobremesaActionPerformed
         Sobremesa s = new Sobremesa(this, rootPaneCheckingEnabled);
        s.setLocationRelativeTo(this);
        s.setVisible(true);
    }//GEN-LAST:event_jMenuItemSobremesaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sat_Agl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sat_Agl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sat_Agl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sat_Agl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sat_Agl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPortatil;
    private javax.swing.JButton jButtonSobremesa;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAcerca;
    private javax.swing.JMenuItem jMenuItemPortatil;
    private javax.swing.JMenuItem jMenuItemSobremesa;
    private javax.swing.JMenuItem jMenuItemv1;
    private javax.swing.JMenuItem jMenuItemv2;
    private javax.swing.JMenu jMenuOrdenador;
    private javax.swing.JMenu jMenuVersion;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelGestionTaller;
    // End of variables declaration//GEN-END:variables
}
