/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package di_tarea_3_2_componentebarrasuperior;

import java.awt.Frame;
import javax.swing.JFrame;

/**
 *
 * @author damt207
 */
public class BarraSuperior extends javax.swing.JPanel {

    /**
     * Creates new form BarraSuperior
     */
    public BarraSuperior() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDragBar = new javax.swing.JPanel();
        jPanelMinimize = new javax.swing.JPanel();
        jLabelMinimize = new javax.swing.JLabel();
        jPanelExit = new javax.swing.JPanel();
        jLabelExit = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(32767, 37));
        setMinimumSize(new java.awt.Dimension(175, 37));
        setOpaque(false);

        jPanelDragBar.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanelDragBar.setMaximumSize(new java.awt.Dimension(32767, 37));
        jPanelDragBar.setMinimumSize(new java.awt.Dimension(100, 37));
        jPanelDragBar.setOpaque(false);
        jPanelDragBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelDragBarMouseDragged(evt);
            }
        });
        jPanelDragBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelDragBarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDragBarLayout = new javax.swing.GroupLayout(jPanelDragBar);
        jPanelDragBar.setLayout(jPanelDragBarLayout);
        jPanelDragBarLayout.setHorizontalGroup(
            jPanelDragBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );
        jPanelDragBarLayout.setVerticalGroup(
            jPanelDragBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jPanelMinimize.setMaximumSize(new java.awt.Dimension(37, 37));
        jPanelMinimize.setMinimumSize(new java.awt.Dimension(37, 37));
        jPanelMinimize.setOpaque(false);
        jPanelMinimize.setPreferredSize(new java.awt.Dimension(37, 37));
        jPanelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMinimizeMouseClicked(evt);
            }
        });

        jLabelMinimize.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinimize.setText("_");
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelMinimizeLayout = new javax.swing.GroupLayout(jPanelMinimize);
        jPanelMinimize.setLayout(jPanelMinimizeLayout);
        jPanelMinimizeLayout.setHorizontalGroup(
            jPanelMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMinimizeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMinimize, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelMinimizeLayout.setVerticalGroup(
            jPanelMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMinimizeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMinimize, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelExit.setMaximumSize(new java.awt.Dimension(37, 37));
        jPanelExit.setMinimumSize(new java.awt.Dimension(37, 37));
        jPanelExit.setOpaque(false);
        jPanelExit.setPreferredSize(new java.awt.Dimension(37, 37));
        jPanelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelExitMouseClicked(evt);
            }
        });

        jLabelExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelExit.setText("X");
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelExitMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelExitLayout = new javax.swing.GroupLayout(jPanelExit);
        jPanelExit.setLayout(jPanelExitLayout);
        jPanelExitLayout.setHorizontalGroup(
            jPanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelExit, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelExitLayout.setVerticalGroup(
            jPanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelExit, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelDragBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanelMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDragBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanelMinimize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanelExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    int xMouse;
    int yMouse;
    
    private void jPanelDragBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDragBarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanelDragBarMousePressed

    private void jPanelDragBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDragBarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        JFrame frame = (JFrame) this.getTopLevelAncestor();
        if(frame != null){
            frame.setLocation(x - xMouse, y - yMouse);
        }

    }//GEN-LAST:event_jPanelDragBarMouseDragged

    private void jLabelExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMousePressed
        exit();
    }//GEN-LAST:event_jLabelExitMousePressed

    private void jPanelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelExitMouseClicked
        exit();
    }//GEN-LAST:event_jPanelExitMouseClicked

    private void jPanelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMinimizeMouseClicked
        minimize();
    }//GEN-LAST:event_jPanelMinimizeMouseClicked

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        minimize();
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    
    private void minimize(){
        JFrame frame = (JFrame) this.getTopLevelAncestor();
        if(frame != null){
            frame.setState(Frame.ICONIFIED);
        }
        
    }
    
    private void exit(){
        System.exit(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JPanel jPanelDragBar;
    private javax.swing.JPanel jPanelExit;
    private javax.swing.JPanel jPanelMinimize;
    // End of variables declaration//GEN-END:variables
}
